[tool.poetry]
name = "hw_2"
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
setuptools = "^69.2.0"
wheel = "^0.43.0"
twine = "^5.0.0"
latex-pypi = "0.3"
pdflatex = "^0.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
